remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: The Beacon Chain Dynamics at Merge
description: The Beacon Chain Dynamics at Merge: Validator Life Cycle Visualizations
